//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba2.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity1
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string age { get; set; }
    }
}
